<a href="https://colab.research.google.com/github/JuanRoccia/Google-Colab/blob/main/PPA_Trabajo_Pr%C3%A1ctico_N%C2%B02_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Trabajo Práctico 2 - NumPy***


---



## Ejercicio 1
Definir un script que pida al usuario ingresar 4 valores 𝑎, 𝑏, 𝑐, 𝑑. Generar con éstos dos vectores 𝑢 = (𝑎, 𝑏) y 𝑣 = (𝑐, 𝑑). El script debe imprimir una matriz con los resultados de las operaciones:

```
a. 𝑣 − 𝑢
b. − 𝑣 − 𝑢 
c. 2𝑢 − 𝑣 
d. 1/2𝑢 − 2𝑣
```


In [ ]:
import numpy as np

In [ ]:
# print('Ingrese 4 valores')
# a = input('Primer valor: ')
# b = input('Segundo valor: ')
# c = input('Tercer valor: ')
# d = input('Cuarto valor: ')

In [ ]:
a = 2
b = 4
c = 16
d = 3

In [ ]:
#a. v - u
u = np.array( [a, b] )
v = np.array( [c, d] )
print(f'u = {u} ')
print(f'v = {v} ')

resta = v - u
print(f'v - u = {resta} ')

u = [2 4] 
v = [16  3] 
v - u = [14 -1] 


In [ ]:
#b. -v - u
menos_v = -v - u
print(f'-v - u = {menos_v} ')

-v - u = [-18  -7] 


In [ ]:
#c. 2u - v
multi_resta = (2*u) - v
print(f'2u - v = {multi_resta} ')

2u - v = [-12   5] 


In [ ]:
#d. 1/2u - 2v
div_multi_resta = 1/2*u - 2*v
print(f'1/2u - 2v = {multi_resta} ')

1/2u - 2v = [-12   5] 


## Ejercicio 2
Una tienda de electrodomésticos escribía a mano en el archivo de texto <i>“stock.txt”</i> los productos que vende, junto con el respectivo precio y stock restante. Quieren guardar esta información en bloques de datos más seguros.<br>
Implementar un script que lea los n datos el archivo y genere tres arreglos unidimensionales con los tres tipos de datos del mismo.<br>
<b>Ayuda:</b> Reorganizarlos en una matriz de tres columnas y n filas, y luego dividirla en tres vectores y finalmente arreglar la inconsistencia de tipos.

***File Handling***

In [ ]:
#Archivo .txt original
#Quieren guardar esta información en bloques de datos más seguros

crear_archivo = open('stock.txt','x')
escribir_archivo = open('stock.txt','w')
escribir_archivo.write('''heladera
79999.99
4
microondas
24539.66
8
licuadora
5608.25
13
pava electrica
4950.75
22
exprimidor electrico
2243.33
17''')
escribir_archivo.close()

abrir_archivo = open('stock.txt','r')
print(abrir_archivo.read())

heladera
79999.99
4
microondas
24539.66
8
licuadora
5608.25
13
pava electrica
4950.75
22
exprimidor electrico
2243.33
17


In [ ]:
# script que lea los n datos del archivo

archivo = open('stock.txt','r')
datos = archivo.read().split('\n') #se guarda en lista
archivo.close()
print('Con split() guardo el .txt (bien separado) en la lista: ')
print(datos)

Con split() guardo el .txt (bien separado) en la lista: 
['heladera', '79999.99', '4', 'microondas', '24539.66', '8', 'licuadora', '5608.25', '13', 'pava electrica', '4950.75', '22', 'exprimidor electrico', '2243.33', '17']


***Python Module***

In [ ]:
import numpy as np

datos = np.array(datos) #se guarda en matriz
print('np.array() convierte la lista en matriz: ')
print(datos)

np.array() convierte la lista en matriz: 
['heladera' '79999.99' '4' 'microondas' '24539.66' '8' 'licuadora'
 '5608.25' '13' 'pava electrica' '4950.75' '22' 'exprimidor electrico'
 '2243.33' '17']


In [ ]:
len_datos = len(datos) #cantidad de elementos en lista
filas = int(len_datos / 3) #/producto precio y cantidad
columnas = 3
datos = datos.reshape(filas, columnas) #Organiza la matriz
print(datos)

[['heladera' '79999.99' '4']
 ['microondas' '24539.66' '8']
 ['licuadora' '5608.25' '13']
 ['pava electrica' '4950.75' '22']
 ['exprimidor electrico' '2243.33' '17']]


In [ ]:
[producto, precio, cantidad] = np.split(datos, 3, 1) #asigna su forma correspondiente
print(producto)
print(cantidad)
print(precio)

[['heladera']
 ['microondas']
 ['licuadora']
 ['pava electrica']
 ['exprimidor electrico']]
[['4']
 ['8']
 ['13']
 ['22']
 ['17']]
[['79999.99']
 ['24539.66']
 ['5608.25']
 ['4950.75']
 ['2243.33']]


In [ ]:
# por ultimo convertir los formatos de str, en este caso, precio y cantidad a float.
precio = precio.astype('float')
cantidad = cantidad.astype('int')
print(f'''producto: 
{producto} 
''')
print(f'''cantidad: 
{cantidad} 
''')
print(f'''precio: 
{precio}''')

producto: 
[['heladera']
 ['microondas']
 ['licuadora']
 ['pava electrica']
 ['exprimidor electrico']] 

cantidad: 
[[ 4]
 [ 8]
 [13]
 [22]
 [17]] 

precio: 
[[79999.99]
 [24539.66]
 [ 5608.25]
 [ 4950.75]
 [ 2243.33]]


# **A partir del inciso anterior:**

## Ejercicio 3
Escribir un script que pida un string al usuario con el nombre de un producto, busqué
si se encuentra en el vector, y en cuyo caso imprima su precio y cantidad disponible.


In [ ]:
nombre_producto = input('Ingrese producto: ')
if (nombre_producto in producto):
  pos = np.where(producto == nombre_producto)
  print(f'El precio de {nombre_producto} es de ${precio[pos][0]}. Quedan {cantidad[pos][0]} unidades.')

Ingrese producto: heladera
El precio de heladera es de $79999.99. Quedan 4 unidades.


## Ejercicio 4
4. Escribir una función comprar(producto) que reciba un string con el nombre de
un producto, verifique si existe o hay disponibilidad, y en dicho caso disminuya la
cantidad disponible y retornará Verdadero, en cualquier otro caso deberá devolver
Falso.

In [ ]:
# Funcion comprar producto
def comprar_producto(producto_solicitado):
  if producto_solicitado in producto: 
    pos = np.where(producto_solicitado == producto) 
    if cantidad[pos] > 0: # Si la cantidad en la posicion del producto solicitado es mayor a cero entonces hay disponibilidad.
      cantidad[pos] = cantidad[pos] - 1 # se le resta el prodcuto solicitado (se resta realmente en la matriz? o es solo la resta de la posicion solicitada?)
      return True, f'Se retiro {producto_solicitado} ', f'Quedan {cantidad[pos][0]} unidades.'
    else:
      return False, 'No hay stock.'
  else:
    return False, 'No existe el producto.'

In [ ]:
# Que reciba un string con el nombre de un producto
print(cantidad[pos])
comprar_producto(input("Solicitar producto: "))
print(cantidad[pos])

[4]
Solicitar producto: heladera
[3]


In [ ]:
print(datos)# matriz original

[['heladera' '79999.99' '4']
 ['microondas' '24539.66' '8']
 ['licuadora' '5608.25' '13']
 ['pava electrica' '4950.75' '22']
 ['exprimidor electrico' '2243.33' '17']]


## Ejercicio 5
Escribir una función Agregar(producto, precio, cantidad) y
Reponer(producto, cantidad). La primera añadirá un nuevo elemento a los
tres vectores (en caso de que no exista en la misma), la segunda aumentará la
cantidad disponible de dicho producto, en caso de que el mismo exista. Ambas
retornarán Verdadero o Falso según corresponda.

In [ ]:
# La funcion reponer(producto, cantidad) aumentará la cantidad de dicho producto,
# en caso de que el mismo exista.
def reponer_producto(producto_repuesto, cantidad_a_reponer):
  if (producto_repuesto in producto):
    pos = np.where(producto == producto_repuesto)
    cantidad[pos] = cantidad[pos] + cantidad_a_reponer
    return True, f'Se repuso el producto: {producto_repuesto}. Total: {cantidad[pos][0]} '
  else:
    return False, f'No existe el producto.'

In [ ]:
reponer_producto(input('Producto a reponer: '), float(input('Cantidad: ')))

Producto a reponer: heladera
Cantidad: 1


(True, 'Se repuso el producto: heladera. Total: 4 ')

In [ ]:
# La función Agregar(producto, precio, cantidad)
# Añadirá un nuevo elemento a los tres vectores (en caso de que no exista en la misma).
def agregar_producto(producto, precio, cantidad, producto_nuevo, precio_nuevo, cantidad_nuevo):
  if producto_nuevo in producto:
    return False, 'The product already exist.'
  else:
    producto = np.append(producto, producto_nuevo)
    precio = np.append(precio, precio_nuevo)
    cantidad = np.append(cantidad, cantidad_nuevo)
    return True, producto, precio, cantidad

In [ ]:
agregar_producto(producto,
                 precio,
                 cantidad,
                 input('Producto nuevo: '),
                 float(input('Precio: ')),
                 int(input('Cantidad: '))
                 )

Producto nuevo: TOMACO
Precio: 199.99
Cantidad: 1


(True, array(['heladera', 'microondas', 'licuadora', 'pava electrica',
        'exprimidor electrico', 'TOMACO'], dtype='<U20'), array([79999.99, 24539.66,  5608.25,  4950.75,  2243.33,   199.99]), array([ 4,  8, 13, 22, 17,  1]))

## Ejercicio 6
Se desea implementar un sistema de lotería virtual. A continuación se detallan los
pasos a seguir para desarrollar un prototipo del proyecto. Se detallan los pasos a
seguir acompañado de observaciones a tener en cuenta para cuando deban
preparar sus propios proyectos.

a. Primero generar la combinación del billete ganador en un vector. El billete
deberá contener cuatro (4) números aleatorios en el rango [0 ; 5].
Obs: El rango de los números aleatorios es muy acotado. La razón de esto
se explicará en el inciso c

In [ ]:
import numpy as np

ganador = np.random.randint(0, 5, size=4)
print(ganador)

[0 3 3 4]


b. Debemos generar los billetes de los participantes. Crearemos una matriz a
cuyas filas asignaremos 10 billetes aleatorios (con las mismas restricciones
del billete ganador).<br>

Obs: Reutilizar el código de generación del billete ganador para generar las
filas. Puede incluso crear una función que lo contenga y devuelva un billete
aleatorio cada vez que se le invoca. La reutilización y modificación de código
que ya poseemos es un aspecto importante a la hora de preparar un
proyecto.<br>

Obs 2: Al final de la consigna hay dos ideas comunes para esto. Primero
implementar su propia idea y luego leer las sugerencias para ganar una
nueva perspectiva.


In [ ]:
participantes = np.random.randint(0,5,size=(10,4))
print(participantes)

[[3 1 1 2]
 [2 0 1 0]
 [3 2 1 0]
 [1 0 4 2]
 [0 4 0 0]
 [0 4 4 4]
 [4 1 4 2]
 [4 4 0 4]
 [1 2 0 1]
 [4 4 2 2]]


In [ ]:
participantes = np.random.randint(0,5,size=4)
for ind in range(0,9,1):
  boleto = np.random.randint(0,5,size=4)
  participantes = np.vstack((participantes, boleto))
print(participantes, boleto) #boleto no va

[[4 3 2 3]
 [2 1 0 4]
 [4 0 3 3]
 [3 3 2 1]
 [3 2 4 3]
 [1 3 2 3]
 [0 4 4 1]
 [2 3 1 3]
 [4 4 2 4]
 [1 2 1 1]] [1 2 1 1]


c. Los ganadores serán aquellos que posean coincidencias del mismo número
en la misma posición que el billete ganador. Escribir un código que
devuelva un arreglo con la cantidad de coincidencias de cada participante.
Ejemplo:

```
Billete ganador: [3 2 0 5 4 3 1]
Billete participante 1: [2 4 1 5 2 3 1] 1 coincidencias.
Billete participante 2: [1 5 1 4 3 1 3] 0 coincidencias.
Billete participante 2: [4 1 0 5 2 3 0] 3 coincidencias.
Arreglo devuelto: [1 0 3]
```
Obs: La razón de elegir un rango de números aleatorios pequeño en el
inciso a es para poder comprobar las coincidencias. Si eligiéramos el rango
de [0 ; 99] sería difícil que en esta pequeña prueba tuviéramos muchas
coincidencias, sin embargo al elegir un rango más pequeño seguramente
podremos comprobar el funcionamiento de nuestro programa. Al verificar que
el funcionamiento es correcto podremos simplemente cambiar los parámetros
del código para tener rango aleatorio más grande, distinta cantidad de
números por billete y cantidad de participantes más grande.

In [ ]:
print(participantes[0])
print(ganador)

[4 3 2 3]
[0 3 3 4]


In [ ]:
coin_part = np.where(participantes[0] == ganador) # Coincidencias en formato tupla
print(coin_part[0])

coin_arr = np.asarray(coin_part)                  # Coincidencias del participante en formato arreglo
print(coin_arr[0])

aciertos_totales = coin_arr.size
print(aciertos_totales)

[1]
[1]


In [ ]:
#repetir lo mismo las 9 veces restantes (10 billetes)

In [ ]:
coin_part = np.where(participantes[0] == ganador)         # Coincidencias del participante en formato tupla
coin_arr = np.asarray(coin_part)                          # Coincidencias del participante en formato arreglo
aciertos_totales = coin_arr.size

for ind in range(1,9,1):
  coin_part = np.where(participantes[ind] == ganador)     # Coincidencias del participante en formato tupla
  coin_arr = np.asarray(coin_part)                        # Coincidencias del participante en formato arreglo
  aciertos_totales = np.vstack((aciertos_totales, coin_arr.size))
print(aciertos_totales)

[[1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]]


d. Opcional 1: Luego de tener el programa listo, crear una función que tome
como parámetros cantidad de números por billete, rango de números
aleatorios, y cantidad de participantes. La función debe devolver por un lado
el billete ganador y por otro la matriz con los billetes de los participantes.


In [ ]:
import numpy as np

def loteria(numeros_por_billete, rango_aleatorio, cantidad_participantes):
  billete_ganador = np.random.randint(0, rango_aleatorio, size=numeros_por_billete)
  participantes = np.random.randint(0,rango_aleatorio,size=(cantidad_participantes,numeros_por_billete))

  return 'Billete banador: ',billete_ganador, 'Billetes participantes: ',participantes

loteria(4, 5, 10)

('Billete banador: ',
 array([1, 3, 1, 1]),
 'Billetes participantes: ',
 array([[1, 4, 4, 3],
        [4, 0, 2, 3],
        [3, 2, 4, 2],
        [0, 2, 0, 1],
        [3, 0, 2, 0],
        [1, 2, 3, 0],
        [4, 2, 2, 0],
        [1, 0, 3, 3],
        [3, 1, 3, 0],
        [0, 3, 2, 1]]))

e. Opcional 2: Crear una función que tome como parámetros el billete ganador y
la matriz de billetes de participantes, y devuelva el número del participante
que tenga el billete ganador (en caso que lo haya), o [-1] si ningún
participante ganó. Ejemplo de encabezado:

```
Comprobar_ganador (billete_ganador, participantes)
```
**Sugerencia:** Para comprobar, pueden “sembrar” la combinación ganadora,
es decir, reemplazar alguna fila de los participantes por la combinación del
ticket ganador. De esta forma se aseguran que exista la combinación y la
función devuelva un resultado.

In [ ]:
# coin_part = np.where(participantes[ind] == billete_ganador)     
# coin_arr = np.asarray(coin_part)                                
# aciertos_totales = coin_arr.size
# aciertos_totales = np.vstack((aciertos_totales, coin_arr.size))

In [ ]:
# import numpy as np

# def Comprobar_ganador (billete_ganador, participantes):
#   for ind in range(0,9,1):
#     if participante == billete_ganador:
#       return participantes, billete_ganador
#     else:
#       return [-1]

# billete_ganador = np.random.randint(0, 5, size=4)
# participantes = np.random.randint(0,5,size=(10,4))
# Comprobar_ganador(billete_ganador, participantes)

# Ejercicio 7
En toda comunicación digital los datos viajan en formato binario, es decir, cadenas de unos y ceros. Para poder interpretar esta información los datos se envían en “paquetes”, es decir, grupos de tamaño finito.<br>
A continuación se presenta la señal recibida en una comunicación digital. Los
paquetes respetan el formato ASCII, por lo tanto cada paquete es de 8 bits (cada 8 números se tiene un carácter).<br>
Ejemplo: El paquete ‘01000001’ corresponde al carácter “A”, mientras que el
‘010101010’ es el carácter ‘a’. La señal :‘01000001010101010’ es una señal de dos paquetes que contiene el mensaje “Aa”.<br>
La comunicación que debe descifrar contiene nueve (9) paquetes de ocho (8) bits
cada uno. Separar cada uno de los paquetes y mostrar el mensaje descifrado.
Para convertir cada paquete en su carácter ASCII usar la siguiente expresión:
```
chr(int('010101010',2))
```
Donde la secuencia insertada entre comillas es la combinación ASCII del carácter.<br>
Ejemplo de uso:
```
x = chr(int('010101010',2))
print(x)
```
Señal a decodificar:
```
010010000110111101101100011000010100110101110101011011100110010001101111
```
Tabla de código ASCII básico (de referencia): http://sticksandstones.kstrom.com/appen.htm

In [ ]:
import numpy as np

arr = np.array(['010010000110111101101100011000010100110101110101011011100110010001101111'])

print(arr[0:8])

['010010000110111101101100011000010100110101110101011011100110010001101111']


In [ ]:
# cadena[inicio:final:saltos]
lista = []
señal = "010010000110111101101100011000010100110101110101011011100110010001101111"

pos1 = 0
pos2 = 8

for num in señal:
  lista.append(señal[pos1:pos2])
  arr = np.append([ lista ], [])
  pos1 += 8
  pos2 += 8
  if señal[pos1:pos2] == '':
    break
# print(lista)
print(arr)

['01001000' '01101111' '01101100' '01100001' '01001101' '01110101'
 '01101110' '01100100' '01101111']


In [ ]:
for paquete in arr:  
  x = chr(int(paquete,2))
  print(x, end=' ')

H o l a M u n d o 